app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('api/token/',
         TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('api/token/refresh/',
         TokenRefreshView.as_view(),
         name='token_refresh'),
    path('api/user/', include('user.urls')),
    path('api/albums/', include('album.urls')),
    path('docs/',
         TemplateView.as_view(template_name='swagger.html'),
         name='documentation'),
    path('',
         TemplateView.as_view(template_name='index.html'),
         name='main-page')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

app/user/urls.py
from django.urls import path

from . import views as api_views

app_name = 'user'

urlpatterns = [
    path('create/',
         api_views.CreateUserAPIView.as_view(),
         name='create-user'),
    path('me/', api_views.UserDetailAPIView.as_view(), name='detail-user'),
    path('me/upload-image/',
         api_views.UserImageUploadAPIView.as_view(),
         name='upload-image-user'),
    path('change-password/',
         api_views.UserPasswordChangeAPIView.as_view(),
         name='change-user-password'),
    path('reset-password/',
         api_views.PasswordResetRequestAPIView.as_view(),
         name='reset-password'),
    path('reset-password-confirm/',
         api_views.PasswordResetConfirmAPIView.as_view(),
         name='reset-password-confirm'),
    path('activate/<uidb64>/<token>/',
         api_views.ActivateUserAPIView.as_view(),
         name='activate-user')
]

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Mateusz Kłusowski">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>MK - Album Project</title>
    <style>
        #contactEmail:hover{
            cursor: grabbing;
        }
        #token:hover{
            cursor: grabbing;
        }
        body{
            background-color: #F9F7F5;
        }
    </style>
</head>
<body>
    <div class="container-fluid" style="padding: 0;">
        <div class="d-flex flex-column align-items-center justify-content-center">
            <a href="{% url 'main-page' %}" class="h1 disabled nav-link disabled" style="color: black;">Album Project</a>
            <p class="h5 text-muted">Mateusz Kłusowski <small class="text-muted" id="copyRight"></small></p>
            <p class="text-muted" id="contactEmail" onclick="copyEmail()">klusowskimat@gmail.com <small id="copyStatus">(click to copy)</small></p>
            <ul class="nav nav-pills nav-fill mb-5">
                <li class="nav-item">
                  <a class="nav-link" href="https://github.com/mateuszklusowski" target="_blank">GitHub</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'documentation' %}" target="_blank">Documentation</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'token_obtain_pair' %}">Obtain token</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:create-user' %}">Create user</a>
                </li>
            </ul>
            <article class="w-50 lead">
                <h3>Hey There!</h3>
                My name is Mateusz. I am a self-taught programmer who started learning out of curiosity. I would like to work with experienced engineers to learn best practices and develop my skills.<br><br>
                A digital album REST API is a project that involves creating a server-side application programming interface (API) that enables clients to interact with a digital album stored on a server. The API allows clients to retrieve information about the album, such as its title and images list, as well as perform actions on the album, such as adding or removing images. The API follows the REST architectural style.<br><br>
                To make full use of the application, you need to create an <a href="{% url 'user:create-user' %}">account</a> and obtain an<a href="{% url 'token_obtain_pair' %}"> access token</a>.<br><br>
                The <a href="{% url 'documentation' %}">Documentation</a> allows you to test the endpoints, but you can also do this using a browser.<br>
                Request header: <code>Authorization:&nbsp;</code>Bearer&nbsp;&nbsp;<code>&lt;access_token&gt;</code>
            </article>
        </div>
    </div>
    <script>
        document.getElementById('copyRight').innerHTML = '© ' + new Date().getFullYear() + ''

        function copyEmail(){
        const text = (document.getElementById('contactEmail').textContent.slice(0,22));
        navigator.clipboard.writeText(text).then(() => {
            document.getElementById('copyStatus').innerText = '(copied)'
          });
        }
    </script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

app/templates/swagger.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Swagger</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
    const ui = SwaggerUIBundle({
        url: "{% static 'schema.yml' %}",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        defaultModelsExpandDepth: -1,
        requestInterceptor: (request) => {
          request.headers['X-CSRFToken'] = "{{ csrf_token }}"
          return request;
        }
      })
    </script>
  </body>
</html>